#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_MOTOR_CS40L2X)		+= cs40l2x.o cs40l2x-tables.o
obj-$(CONFIG_MAX77705_VIBRATOR)        += max77705_vibrator.o
obj-$(CONFIG_SEC_VIBRATOR) += sec_vibrator.o
