# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_EXYNOS9820) += exynos/exynos9820.dtb
dtb-$(CONFIG_SOC_EXYNOS9825) += exynos/exynos9825.dtb

dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_25.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_18.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_24.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_17.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_19.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_20.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTE) += samsung/exynos9820-beyond0lte_eur_open_22.dtbo

dtbo-$(CONFIG_MODEL_BEYOND0LTEKS) += samsung/exynos9820-beyond0lte_kor_20.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTEKS) += samsung/exynos9820-beyond0lte_kor_19.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTEKS) += samsung/exynos9820-beyond0lte_kor_25.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTEKS) += samsung/exynos9820-beyond0lte_kor_18.dtbo
dtbo-$(CONFIG_MODEL_BEYOND0LTEKS) += samsung/exynos9820-beyond0lte_kor_17.dtbo

dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_21.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_17.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_18.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_26.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_23.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_22.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_24.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_20.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTE) += samsung/exynos9820-beyond1lte_eur_open_19.dtbo

dtbo-$(CONFIG_MODEL_BEYOND1LTEKS) += samsung/exynos9820-beyond1lte_kor_21.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTEKS) += samsung/exynos9820-beyond1lte_kor_19.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTEKS) += samsung/exynos9820-beyond1lte_kor_26.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTEKS) += samsung/exynos9820-beyond1lte_kor_20.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTEKS) += samsung/exynos9820-beyond1lte_kor_17.dtbo
dtbo-$(CONFIG_MODEL_BEYOND1LTEKS) += samsung/exynos9820-beyond1lte_kor_18.dtbo

dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_25.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_16.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_04.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_18.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_17.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_26.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_20.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_23.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_19.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTE) += samsung/exynos9820-beyond2lte_eur_open_24.dtbo

dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_18.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_24.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_20.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_19.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_17.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_26.dtbo
dtbo-$(CONFIG_MODEL_BEYOND2LTEKS) += samsung/exynos9820-beyond2lte_kor_25.dtbo

dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_07.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_02.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_00.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_08.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_01.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_04.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_06.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_05.dtbo
dtbo-$(CONFIG_MODEL_BEYONDX) += samsung/exynos9820-beyondx_eur_open_03.dtbo

dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_08.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_06.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_00.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_03.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_04.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_07.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_01.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_02.dtbo
dtbo-$(CONFIG_MODEL_BEYONDXKS) += samsung/exynos9820-beyondx_kor_05.dtbo

dtbo-$(CONFIG_MODEL_D1) += samsung/exynos9825-d1_eur_open_21.dtbo
dtbo-$(CONFIG_MODEL_D1) += samsung/exynos9825-d1_eur_open_22.dtbo
dtbo-$(CONFIG_MODEL_D1) += samsung/exynos9825-d1_eur_open_19.dtbo
dtbo-$(CONFIG_MODEL_D1) += samsung/exynos9825-d1_eur_open_18.dtbo
dtbo-$(CONFIG_MODEL_D1) += samsung/exynos9825-d1_eur_open_23.dtbo

dtbo-$(CONFIG_MODEL_D1XKS) += samsung/exynos9825-d1x_kor_19.dtbo
dtbo-$(CONFIG_MODEL_D1XKS) += samsung/exynos9825-d1x_kor_22.dtbo
dtbo-$(CONFIG_MODEL_D1XKS) += samsung/exynos9825-d1x_kor_21.dtbo
dtbo-$(CONFIG_MODEL_D1XKS) += samsung/exynos9825-d1x_kor_23.dtbo
dtbo-$(CONFIG_MODEL_D1XKS) += samsung/exynos9825-d1x_kor_18.dtbo

dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_02.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_18.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_22.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_24.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_23.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_19.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_21.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_17.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_16.dtbo
dtbo-$(CONFIG_MODEL_D2S) += samsung/exynos9825-d2s_eur_open_20.dtbo

dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_22.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_23.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_24.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_19.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_18.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_20.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_21.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_16.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_17.dtbo
dtbo-$(CONFIG_MODEL_D2X) += samsung/exynos9825-d2x_eur_open_02.dtbo

dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_18.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_02.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_16.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_21.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_24.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_23.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_19.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_22.dtbo
dtbo-$(CONFIG_MODEL_D2XKS) += samsung/exynos9825-d2x_kor_17.dtbo

targets += dtbs
DTB_LIST  := $(dtb-y) $(dtbo-y)
always    := $(DTB_LIST)

dtbs: $(addprefix $(obj)/, $(DTB_LIST))

clean-files := *.dtb*
